server:
  port: 19000

spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/with-one-voice/ticketing-service.git
          default-label: develop
          search-paths:
            - config/src/main/resources/config-repo
          basedir: /config-repo
          clone-on-start: true
          force-pull: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.config: DEBUG
