global:
  scrape_interval: 15s  # 메트릭 수집 주기

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:8081']

  - job_name: 'user-service'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]

  - job_name: 'show-service'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]

  - job_name: 'venue-service'
    static_configs:
      - targets: [ 'host.docker.internal:8084' ]

  - job_name: 'ticket-service'
    static_configs:
      - targets: [ 'host.docker.internal:8085' ]

  - job_name: 'seat-service'
    static_configs:
      - targets: [ 'host.docker.internal:8086' ]

  - job_name: 'payment-service'
    static_configs:
      - targets: [ 'host.docker.internal:8087' ]

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:8088']













  - job_name: 'admin-service'
    static_configs:
      - targets: [ 'host.docker.internal:8089' ]
