apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8008"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: notification
          image: joon97/notification-service:latest  # GitHub Actions에서 sed로 SHORT_SHA 대체
          ports:
            - name: notif-port
              containerPort: 8008
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD

            - name: CONFIG_SERVER_URL
              value: http://config-server:19000

            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST

            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: KAFKA_HOST

            - name: MAIL_HOST
              value: smtp.gmail.com
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: MAIL_PASSWORD

            - name: DISCORD_NAME
              value: notification
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DISCORD_WEBHOOK_URL

            - name: SWAGGER_URL
              value: "http://localhost:8080"

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_PASSWORD
                  name: onevoice-secret