apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seat
  template:
    metadata:
      labels:
        app: seat
    spec:
      containers:
        - name: seat
          image: joon97/seat-service:latest
          ports:
            - name: seat-port
              containerPort: 8006
