apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: onevoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: joon97/gateway-service
          ports:
            - containerPort: 8080
              name: gateway-port
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:19000
            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: JWT_SECRET_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: onevoice-secret
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: onevoice-secret