apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: gateway
          image: joon97/gateway-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:19000
            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: JWT_SECRET_KEY
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: onevoice-secret
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: onevoice-secret