apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: joon97/ticket-service:latest  # GitHub Actions에서 SHA로 치환됨
          ports:
            - name: ticket-port
              containerPort: 8005
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD

            - name: CONFIG_SERVER_URL
              value: http://config-server:19000

            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST

            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: KAFKA_HOST

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: onevoice-secret

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: onevoice-secret

            - name: SWAGGER_URL
              value: "http://localhost:8080"

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_PASSWORD
                  name: onevoice-secret