server:
  port: 8001

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/auth_db
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:sa}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 36000000

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /v3/api-docs

swagger:
  server-url: http://localhost:8080/api/auth

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    export:
      prometheus:
        enabled: true