apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: onevoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: joon97/auth-service
          ports:
            - containerPort: 8001
              name: auth-port
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: onevoice-secret
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: onevoice-secret
            - name: CONFIG_SERVER_URL
              value: http://config-server:19000

            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: JWT_SECRET_KEY
            - name: SWAGGER_URL
              valueFrom:
                secretKeyRef:
                  key: SWAGGER_URL
                  name: onevoice-secret
