grafana:
  adminUser: admin
  adminPassword: admin

  defaultDashboardsEnabled: false  # 기본 대시보드 비활성화

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.monitoring.svc:3100

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      kubernetes-pod-metrics:
        gnetId: 747
        revision: 1
        datasource: Prometheus
      loki-logs:
        gnetId: 13639
        revision: 1
        datasource: Loki
      prometheus-stats:
        gnetId: 3662
        revision: 2
        datasource: Prometheus
