loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: gp2         # Kops - AWS EBS(gp2)를 사용
    accessModes:
      - ReadWriteOnce
    size: 10Gi                    # 초기에는 10Gi 정도로 시작 가능 (운영에 따라 조정)

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc:3100/loki/api/v1/push

grafana:
  enabled: false