loki:
  enabled: true
  persistence:
    enabled: false                 # 디스트 저장 비활성화

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki.monitoring.svc:3100/loki/api/v1/push

grafana:
  enabled: false                   # 이미 설치된 경우 false로 유지