namespace: monitoring

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: latest
  service:
    type: ClusterIP
    port: 9090
  scrapeInterval: 15s

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: latest
  service:
    type: ClusterIP
    port: 3000
  admin:
    user: admin
    password: admin
  oauth:
    enabled: false  # OAuth 설정 시 true로 변경
  dashboards:
    enabled: true
    folder: /etc/grafana/provisioning/dashboards/json  # 대시보드 JSON 경로

loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "2.9.4"
  service:
    type: ClusterIP
    port: 3100
  promtail:
    enabled: true  # Loki 배포 시 Promtail도 함께 배포
