apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: joon97/config-server:latest
          ports:
            - name: config-port
              containerPort: 19000

          env:
          - name: EUREKA_HOST
            valueFrom:
              secretKeyRef:
                name: onevoice-secret
                key: EUREKA_HOST
