apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: onevoice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: joon97/eureka-server:latest
          ports:
            - name: eureka-port
              containerPort: 8761
