apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: joon97/auth-service:latest  # Actions에서 sed로 SHA 버전으로 대체됨
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: "postgres"         # K8s 내 postgres 서비스 이름
            - name: DB_PORT
              value: "5433"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: JWT_SECRET_KEY
            - name: SWAGGER_URL
              value: "http://localhost:8080"
            - name: CONFIG_SERVER_URL
              value: http://config-server:19000
            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: eureka-host-secret
                  key: EUREKA_HOST
