apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: {{ .Values.loki.service.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /data/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: storage
          emptyDir: { }
