apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show
  template:
    metadata:
      labels:
        app: show
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8003"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: show
          image: joon97/show-service:latest  # GitHub Actions에서 SHA 버전으로 대체
          ports:
            - name: show-port
              containerPort: 8003
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD

            - name: CONFIG_SERVER_URL
              value: http://config-server:19000

            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST

            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: KAFKA_HOST

            - name: SWAGGER_URL
              value: "http://localhost:8080"

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: onevoice-secret

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: onevoice-secret

            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KAFKA_PASSWORD
                  name: onevoice-secret