apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show
  template:
    metadata:
      labels:
        app: show
    spec:
      containers:
        - name: show
          image: joon97/show-service:latest
          ports:
            - name: show-port
              containerPort: 8003
