apiVersion: v1
kind: Service
metadata:
  name: seat-service
  namespace: onevoice
  labels:
    app: seat
spec:
  selector:
    app: seat
  ports:
    - name: metrics
      port: 8006           # 외부에서 접근할 포트
      targetPort: seat-port   # 컨테이너 내부 포트 (Deployment의 containerPort와 일치)
  type: ClusterIP        # 내부 서비스용 (기본값)
