apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url:
          http://prometheus:{{ .Values.prometheus.service.port }}
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url:
          http://loki:{{ .Values.loki.service.port }}
