apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: grafana
  ports:
    - port: {{.Values.grafana.service.port}}
      targetPort: {{.Values.grafana.service.port}}
  type: {{.Values.grafana.service.type}}
