name: Java CI (Spring Boot MSA)

on:
  push:
    branches: [ "main", "develop", "release/**" ]
  pull_request:
    branches: [ "main", "develop", "release/**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant permission to gradlew
        run: chmod +x ./gradlew

      # 테스트 없는 인프라 서비스 빌드만
      - name: Build infra modules (config, eureka, gateway)
        run: ./gradlew :config:build :eureka:build :gateway:build -x test --no-daemon

      # 테스트 포함 도메인 서비스 빌드 및 테스트
      - name: Build & Test domain modules
        run: |
          ./gradlew :auth:build \
                     :user:build \
                     :show:build \
                     :venue:build \
                     :ticket:build \
                     :seat:build \
                     :payment:build \
                     :notification:build \
                     :admin:build \
                     --no-daemon
