apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: joon97/admin-service:latest
          ports:
            - name: admin-port
              containerPort: 8009
          env:
            - name: CONFIG_SERVER_URL
              value: http://config-server:19000
