apiVersion: apps/v1
kind: Deployment
metadata:
  name: venue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venue
  template:
    metadata:
      labels:
        app: venue
    spec:
      containers:
        - name: venue
          image: joon97/venue-service:latest
          ports:
            - name: venue-port
              containerPort: 8004
