apiVersion: apps/v1
kind: Deployment
metadata:
  name: venue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venue
  template:
    metadata:
      labels:
        app: venue
    spec:
      containers:
        - name: venue
          image: joon97/venue-service:latest  # GitHub Actions에서 SHA로 치환됨
          ports:
            - name: venue-port
              containerPort: 8004
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PORT

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: DB_PASSWORD

            - name: CONFIG_SERVER_URL
              value: http://config-server:19000

            - name: EUREKA_HOST
              valueFrom:
                secretKeyRef:
                  name: onevoice-secret
                  key: EUREKA_HOST

            - name: SWAGGER_URL
              value: "http://localhost:8080"
